import Head from "next/head";
import { Inter } from "@next/font/google";
import { getAllPosts } from "../lib/notionAPI";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },

    // 60秒ごとに新しいものに更新していく
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div></div>
        <h1 className="text-3xl font-bold underline flex center items-center">
          Hello world!
        </h1>
      </main>
    </>
  );
}
